name: Action workflow
run-name: Action run - ${{ inputs.environment }} 

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - test
          - uat
          - prod
        required: true
        description: "Deployment Environment"

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running against ${{ inputs.environment }}"
        
    
